CREATE TABLE IF NOT EXISTS earthquake_archive_events (
    eventid VARCHAR(64) PRIMARY KEY,
    source_row_id BIGINT NULL,
    source VARCHAR(64) NULL,
    mag DECIMAL(5,2) NULL,
    depth_km DECIMAL(8,2) NULL,
    latitude DECIMAL(10,7) NULL,
    longitude DECIMAL(10,7) NULL,
    place VARCHAR(512) NULL,
    wib_date VARCHAR(20) NULL,
    wib_time VARCHAR(20) NULL,
    datetime_utc DATETIME(6) NULL,
    type VARCHAR(32) NULL,
    status VARCHAR(32) NULL,
    properties JSON NULL,
    has_moment_tensor BOOLEAN NOT NULL DEFAULT FALSE,
    has_felt_data BOOLEAN NOT NULL DEFAULT FALSE,
    has_damage_data BOOLEAN NOT NULL DEFAULT FALSE,
    has_narasi BOOLEAN NOT NULL DEFAULT FALSE,
    has_m5_payload BOOLEAN NOT NULL DEFAULT FALSE,
    has_eq_phase BOOLEAN NOT NULL DEFAULT FALSE,
    source_updated_at DATETIME(6) NOT NULL,
    source_sequence BIGINT UNSIGNED NOT NULL DEFAULT 0,
    received_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    INDEX idx_earthquake_datetime (datetime_utc),
    INDEX idx_earthquake_mag (mag),
    INDEX idx_earthquake_status (status),
    INDEX idx_earthquake_location (latitude, longitude),
    INDEX idx_earthquake_source_row (source_row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

